package com.ws.cxf.spring.tomcat;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HelloServerImplService service = new HelloServerImplService();
 * HelloService portType = service.getHelloServerImplPort();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HelloServerImplService", targetNamespace = "http://server.tomcat.spring.cxf.ws.com/", wsdlLocation = "http://localhost:8080/WebService_CXF_Spring_Tomcat_Server_1/ws/sayHello?wsdl")
public class HelloServerImplService extends Service {

	private final static URL HELLOSERVERIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ws.cxf.spring.tomcat.HelloServerImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ws.cxf.spring.tomcat.HelloServerImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/WebService_CXF_Spring_Tomcat_Server_1/ws/sayHello?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WebService_CXF_Spring_Tomcat_Server_1/ws/sayHello?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HELLOSERVERIMPLSERVICE_WSDL_LOCATION = url;
	}

	public HelloServerImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloServerImplService() {
		super(HELLOSERVERIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://server.tomcat.spring.cxf.ws.com/",
				"HelloServerImplService"));
	}

	/**
	 * 
	 * @return returns HelloService
	 */
	@WebEndpoint(name = "HelloServerImplPort")
	public HelloService getHelloServerImplPort() {
		return super.getPort(new QName(
				"http://server.tomcat.spring.cxf.ws.com/",
				"HelloServerImplPort"), HelloService.class);
	}

}
